---
- name: "3.1.1 Verify if IP forwarding is disabled (Scored)"
  block:
    - name: "3.1.1 verify if net.ipv4.ip_forward is set to 0"
      command: grep -Fxq "net.ipv4.ip_forward=0" /etc/sysctl.conf
      register: output_1
    - fail:
        msg: "3.1.1 failed to verify if IP forwarding is disabled, net.ipv4.ip_forward is not set to 0"
      when: output_1.rc != 0
    - name: "3.1.1 verify if net.ipv6.conf.all.forwarding is set to 0"
      command: grep -Fxq "net.ipv6.conf.all.forwarding=0" /etc/sysctl.conf
      register: output_2
    - fail:
        msg: "3.1.1 failed to verify if IP forwarding is disabled, net.ipv6.conf.all.forwarding is not set to 0"
      when: output_2.rc != 0
  tags:
    - cis
    - cis.3
    - cis.3.1
    - cis.3.1.1
    - scored
