---
- name: "3.5.3 Verify if RDS is disabled (Not Scored)"
# Verifying the RDS disablement settings in /etc/modprobe.d/modprobe.conf
  vars:
    modprobe_conf: "/etc/modprobe.d/modprobe.conf"
    rds_settings_expected: "install rds /bin/true"
  block:
    - name: "3.5.3 verify if RDS is disabled"
      command: grep -Fq {{ rds_settings_expected }} {{ modprobe_conf }}
      register: output_1
    - fail:
        msg: "3.5.3 failed to verify if RDS is disabled, settings of RDS is not expected in /etc/modprobe.d/modprobe.conf"
      when: output_1.rc != 0
  tags:
    - cis
    - cis.3
    - cis.3.5
    - cis.3.5.3
    - notscored
