---
- name: "3.5.1 Verify if DCCP is disabled (Not Scored)"
# Verifying the DCCP disablement settings in /etc/modprobe.d/modprobe.conf
  vars:
    modprobe_conf: "/etc/modprobe.d/modprobe.conf"
    dccp_settings_expected: "install dccp /bin/true"
  block:
    - name: "3.5.1 verify if DCCP is disabled"
      command: grep -Fq {{ dccp_settings_expected }} {{ modprobe_conf }}
      register: output_1
    - fail:
        msg: "3.5.1 failed to verify if DCCP is disabled, settings of DCCP is not expected in /etc/modprobe.d/modprobe.conf"
      when: output_1.rc != 0
  tags:
    - cis
    - cis.3
    - cis.3.5
    - cis.3.5.1
    - notscored
