---
- name: "3.5.4 Verify if TIPC is disabled (Not Scored)"
# Verifying the TIPC disablement settings in /etc/modprobe.d/modprobe.conf
  vars:
    modprobe_conf: "/etc/modprobe.d/modprobe.conf"
    tipc_settings_expected: "install tipc /bin/true"
  block:
    - name: "3.5.4 verify if TIPC is disabled"
      command: grep -Fq {{ tipc_settings_expected }} {{ modprobe_conf }}
      register: output_1
    - fail:
        msg: "3.5.4 failed to verify if TIPC is disabled, settings of TIPC is not expected in /etc/modprobe.d/modprobe.conf"
      when: output_1.rc != 0
  tags:
    - cis
    - cis.3
    - cis.3.5
    - cis.3.5.4
    - notscored
