---
- name: "5.2.2 Ensure SSH Protocol is set to 2 (Scored)"
  vars:
    file: /etc/ssh/sshd_config
  lineinfile:
    path: "{{ file }}"
    line: "Protocol 2"

#- name: "5.2.2 - restart sshd"
#  service:
#    name: "sshd"
#    enabled: true
#    state: restarted
  tags:
      - cis
      - cis.5
      - cis.5.2
      - cis.5.2.2
      - scored
