---
- name: "5.4.1.4 Ensure inactive password lock is 30 days or less (Scored)"
  vars:
    file: /etc/default/useradd
    cis_pass_inactive_lock: 30
  block:
    - name: "5.4.1.4 - Obtain a list of user accounts"
      shell: "egrep ^[^:]+:[^\\!*] /etc/shadow | cut -d: -f1"
      register: egrep_5_4_1_4
      check_mode: no
      changed_when: False
    - name: "5.4.1.4 - Ensure inactive password lock is 30 days or less."
      lineinfile:
        path: "{{ file }}"
        regexp: "^INACTIVE\\s+"
        line: "INACTIVE {{ cis_pass_inactive_lock }}"
    - name: "5.4.1.4 - Set password inactive password lock."
      command: "chage --inactive {{ cis_pass_inactive_lock }} {{ my_result }}"
      with_items: "{{ egrep_5_4_1_4.stdout_lines }}"
      loop_control:
        loop_var: my_result
  tags:
      - cis
      - cis.5
      - cis.5.4
      - cis.5.4.1
      - cis.5.4.1.4
      - scored
