---
- name: "3.1.1 Ensure IP forwarding is disabled (Scored) set net.ipv4.ip_forward to 0"
  sysctl:
    name: net.ipv4.ip_forward
    value: 0
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  tags:
      - cis
      - cis.3
      - cis.3.1
      - cis.3.1.1
      - scored
- name: "set net.ipv6.conf.all.forwarding"
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: 0
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  tags:
      - cis
      - cis.3
      - cis.3.1
      - cis.3.1.1
      - scored


