---
- name: "4.1.17 Verify that system administrator actions (sudolog) are collected (Scored)"
  vars:
    audit_rules: /etc/audit/rules.d/audit.rules
  shell: |
      grep -q '^-w /var/log/sudo.log -p wa -k actions$' {{ audit_rules }}
  tags:
      - cis
      - cis.4
      - cis.4.1
      - cis.4.1.17
      - scored
