---
- name: "4.1.1.3 Ensure audit logs are not automatically deleted (Scored)"
  vars:
    audit_config: /etc/audit/auditd.conf
  lineinfile:
    path: "{{ audit_config }}"
    line: "max_log_file_action = keep_logs"
  tags:
      - cis
      - cis.4
      - cis.4.1
      - cis.4.1.1
      - cis.4.1.1.3
      - scored
