---
- name: "4.2.1.4 Verify that rsyslog default file permissions configured (Scored)"
  vars:
    rsyslog_conf: /etc/rsyslog.conf
  shell: |
      grep -q '^$FileCreateMode 0640' "{{ rsyslog_conf }}"
  tags:
      - cis
      - cis.4
      - cis.4.2
      - cis.4.2.1
      - cis.4.2.1.4
      - scored
