---
- name: "4.2.2.2 Verify that journald is configured to compress large log files (Scored)"
  vars:
    journald_conf: /etc/systemd/journald.conf
  shell: |
    grep -q '^Compress=yes$' "{{ journald_conf }}"
  tags:
      - cis
      - cis.4
      - cis.4.2
      - cis.4.2.2
      - cis.4.2.2.2
      - scored
