---
- name: "4.2.2.3 Verify that journald is configured to write logfiles to persistent disk (Scored)"
  vars:
    journald_conf: /etc/systemd/journald.conf
  shell: |
    grep -q '^Storage=persistent$' "{{ journald_conf }}"
  tags:
      - cis
      - cis.4
      - cis.4.2
      - cis.4.2.2
      - cis.4.2.2.3
      - scored
